name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: psf/black@stable
        with:
          options: "--check --verbose --include '(\\.pyi?|\\.ipynb|workbench)$'"
